<?php
function invoicely_menu()
{
    $items['receipts'] = array(
        'title' => 'My Receipts',
        'description' => 'Administer My Receipts',
        'page callback' => 'invoicely_receipts_list',
        'file' => 'invoicely.receipts.inc',
        'access arguments' => array('view receipts')
    );
    $items['receipts/add'] = array(
        'title' => 'Add new Receipt',
        'description' => 'Add a new Receipt',
        'page callback' => 'invoicely_receipts_add',
        'file' => 'invoicely.receipts.inc',
        'access arguments' => array('view receipts')
    );
    $items['invoices'] = array(
      'title' => 'My Invoices',
      'description' => 'Administer My Invoices',
      'page callback' => 'invoicely_invoices_list',
      'file' => 'invoicely.invoices.inc',
      'access arguments' => array('view invoices')
    );
    $items['mileage'] = array(
      'title' => 'My Mileage',
      'description' => 'Administer My Mileage',
      'page callback' => 'invoicely_mileage_dashboard',
      'file' => 'invoicely.mileage.inc',
      'access arguments' => array('view mileage')
    );

    return $items;
}

/**
 * Implements hook_permission().
 *
 * Defines a permission for managing the mail_system variable.
 */
function invoicely_permission()
{
    return array(
        'view invoices' => array(
            'title' => t('View Invoices'),
            'description' => t('Allow a user to view their own invoices'),
        ),
        'view receipts' => array(
            'title' => t('View Receipts'),
            'description' => t('Allow a user to view their own receipts'),
        ),
        'view mileage' => array(
          'title' => t('View Mileage'),
          'description' => t('Allow a user to view their own mileage log'),
        ),
    );
}

/**
 * Crunch through a view
 *
 * @param string $file File of the template to call.
 * @param array|object $view Optional view array.
 *
 * @return string
 */
function invoicely_template_view($file, $view = null)
{
    $file = DRUPAL_ROOT . "/" . drupal_get_path('module', 'invoicely') . "/" . $file;
    if (!file_exists($file)) {
        return "Cannot find {$file}";
    }
    extract((array)$view);
    ob_start();
    require($file);
    $markup = ob_get_contents();
    ob_end_clean();

    return $markup;
}