<?php
function invoicely_menu()
{
    $items['dashboard'] = array(
        'title' => 'My Dashboard',
        'description' => 'Invoicely Dashboard',
        'page callback' => 'invoicely_dash',
        'file' => 'invoicely.dashboard.inc',
        'access arguments' => array('view dashboard')
    );
    $items['receipts'] = array(
        'title' => 'My Receipts',
        'description' => 'Administer My Receipts',
        'page callback' => 'invoicely_receipts_dash',
        'file' => 'invoicely.receipts.inc',
        'access arguments' => array('view receipts')
    );
    $items['receipts/list'] = array(
        'title' => 'My Receipts - List',
        'description' => 'Administer My Receipts',
        'page callback' => 'invoicely_receipts_list',
        'file' => 'invoicely.receipts.inc',
        'access arguments' => array('view receipts')
    );
    $items['receipts/add'] = array(
        'title' => 'Add new Receipt',
        'description' => 'Add a new Receipt',
        'page callback' => 'invoicely_receipts_edit',
        'file' => 'invoicely.receipts.inc',
        'access arguments' => array('view receipts')
    );
    $items['receipts/edit/%'] = array(
        'title' => 'Edit Receipt',
        'description' => 'Edit a Receipt',
        'page callback' => 'invoicely_receipts_edit',
        'page arguments'   => array(2),
        'file' => 'invoicely.receipts.inc',
        'access arguments' => array('view receipts')
    );
    $items['receipts/import'] = array(
      'title' => 'Import Receipts',
      'page callback' => 'invoicely_receipts_import',
      'file' => 'invoicely.receipts.import-export.inc',
      'access arguments' => array('view receipts')
    );
    $items['receipts/export'] = array(
      'title' => 'Export Receipts',
      'page callback' => 'invoicely_receipts_export',
      'file' => 'invoicely.receipts.import-export.inc',
      'access arguments' => array('view receipts')
    );
    $items['invoices'] = array(
        'title' => 'My Invoices',
        'description' => 'Administer My Invoices',
        'page callback' => 'invoicely_invoices_dash',
        'file' => 'invoicely.invoices.inc',
        'access arguments' => array('view invoices')
    );
    $items['invoices/add'] = array(
        'title' => 'My Invoices - Add',
        'description' => 'Add new Invoice',
        'page callback' => 'invoicely_invoices_add',
        'file' => 'invoicely.invoices.inc',
        'access arguments' => array('view invoices')
    );
    $items['invoices/list'] = array(
        'title' => 'My Invoices - List',
        'description' => 'Administer My Invoices',
        'page callback' => 'invoicely_invoices_list',
        'file' => 'invoicely.invoices.inc',
        'access arguments' => array('view invoices')
    );
    $items['mileage'] = array(
        'title' => 'My Mileage',
        'description' => 'Administer My Mileage',
        'page callback' => 'invoicely_mileage_dashboard',
        'file' => 'invoicely.mileage.inc',
        'access arguments' => array('view mileage')
    );

    return $items;
}

/**
 * Implements hook_permission().
 *
 * Defines a permission for managing the mail_system variable.
 */
function invoicely_permission()
{
    return array(
        'view dashboard' => array(
            'title' => t("View Dashboard"),
            'description' => t("View own invoicely dashboard"),
        ),
        'view invoices' => array(
            'title' => t('View Invoices'),
            'description' => t('Allow a user to view their own invoices'),
        ),
        'view receipts' => array(
            'title' => t('View Receipts'),
            'description' => t('Allow a user to view their own receipts'),
        ),
        'view mileage' => array(
          'title' => t('View Mileage'),
          'description' => t('Allow a user to view their own mileage log'),
        ),
    );
}

/**
 * Crunch through a view
 *
 * @param string $file File of the template to call.
 * @param array|object $view Optional view array.
 *
 * @return string
 */
function invoicely_template_view($file, $view = null)
{
    $file = DRUPAL_ROOT . "/" . drupal_get_path('module', 'invoicely') . "/" . $file;
    if (!file_exists($file)) {
        return "Cannot find {$file}";
    }
    extract((array)$view);
    ob_start();
    require($file);
    $markup = ob_get_contents();
    ob_end_clean();

    return $markup;
}

