<?php
function invoicely_page_alter(){
  drupal_add_js("https://www.google.com/jsapi");
  drupal_add_js('google.load("visualization", "1", {packages:["corechart"]});', 'inline');
}
function invoicely_menu() {
  $items['dashboard']              = array(
    'title'            => 'My Dashboard',
    'description'      => 'Invoicely Dashboard',
    'page callback'    => 'invoicely_dash',
    'file'             => 'invoicely.dashboard.inc',
    'access arguments' => array('view dashboard')
  );
  $items['receipts']               = array(
    'title'            => 'My Receipts',
    'description'      => 'Administer My Receipts',
    'page callback'    => 'invoicely_receipts_dash',
    'file'             => 'invoicely.receipts.inc',
    'access arguments' => array('view receipts')
  );
  $items['receipts/list']          = array(
    'title'            => 'My Receipts - List',
    'description'      => 'Administer My Receipts',
    'page callback'    => 'invoicely_receipts_list',
    'file'             => 'invoicely.receipts.inc',
    'access arguments' => array('view receipts')
  );
  $items['receipts/add']           = array(
    'title'            => 'New',
    'description'      => 'Add a new Receipt',
    'page callback'    => 'invoicely_receipts_edit',
    'file'             => 'invoicely.receipts.inc',
    'access arguments' => array('view receipts')
  );
  $items['receipts/edit/%']        = array(
    'title'            => 'Edit Receipt',
    'description'      => 'Edit a Receipt',
    'page callback'    => 'invoicely_receipts_edit',
    'page arguments'   => array(2),
    'file'             => 'invoicely.receipts.inc',
    'access arguments' => array('view receipts')
  );
  $items['receipts/view/%']        = array(
    'title'            => 'View Receipt',
    'description'      => 'Edit a Receipt',
    'page callback'    => 'invoicely_receipts_edit',
    'page arguments'   => array(2),
    'file'             => 'invoicely.receipts.inc',
    'access arguments' => array('view receipts')
  );
  $items['receipts/import']        = array(
    'title'            => 'Import',
    'page callback'    => 'invoicely_receipts_import',
    'file'             => 'invoicely.receipts.import-export.inc',
    'access arguments' => array('view receipts')
  );
  $items['receipts/export']        = array(
    'title'            => 'Export',
    'page callback'    => 'invoicely_receipts_export',
    'file'             => 'invoicely.receipts.import-export.inc',
    'access arguments' => array('view receipts')
  );
  $items['receipts/repeated/list'] = array(
    'title'            => 'Repeated Receipts - View',
    'page callback'    => 'invoicely_receipts_repeated_list',
    'file'             => 'invoicely.receipts-repeated.inc',
    'access arguments' => array('view receipts')
  );
  $items['receipts/repeated/add']  = array(
    'title'            => 'Repeated Receipts - Add',
    'page callback'    => 'invoicely_receipts_repeated_add',
    'file'             => 'invoicely.receipts-repeated.inc',
    'access arguments' => array('view receipts')
  );
  $items['invoices']               = array(
    'title'            => 'My Invoices',
    'description'      => 'Administer My Invoices',
    'page callback'    => 'invoicely_invoices_dash',
    'file'             => 'invoicely.invoices.inc',
    'access arguments' => array('view invoices')
  );
  $items['invoices/add']           = array(
    'title'            => 'My Invoices - Add',
    'description'      => 'Add new Invoice',
    'page callback'    => 'invoicely_invoices_edit',
    'file'             => 'invoicely.invoices.inc',
    'access arguments' => array('view invoices')
  );
  $items['invoices/edit/%']           = array(
    'title'            => 'My Invoices - Add',
    'description'      => 'Add new Invoice',
    'page callback'    => 'invoicely_invoices_edit',
    'page arguments'   => array(2),
    'file'             => 'invoicely.invoices.inc',
    'access arguments' => array('view invoices')
  );
  $items['invoices/list']          = array(
    'title'            => 'My Invoices - List',
    'description'      => 'Administer My Invoices',
    'page callback'    => 'invoicely_invoices_list',
    'file'             => 'invoicely.invoices.inc',
    'access arguments' => array('view invoices')
  );
  $items['mileage']                = array(
    'title'            => 'My Mileage',
    'description'      => 'Administer My Mileage',
    'page callback'    => 'invoicely_mileage_dashboard',
    'file'             => 'invoicely.mileage.inc',
    'access arguments' => array('view mileage')
  );

  return $items;
}

function invoicely_block_info() {
  $blocks['version'] = array(
    'info' => t('Git Version Control'),
    'weight' => '10',
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['designed-and-developed'] = array(
    'info' => t('Designed & Developed...'),
    'weight' => '10',
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

function invoicely_block_view($delta = '') {
  $block = array();
  switch ($delta) {

    case 'version':
      $block['subject'] = NULL;
      $block['content'] = invoicely_version_control_version();
      return $block;
    case 'designed-and-developed':
      $block['subject'] = NULL;
      $block['content'] = invoicely_designed_and_developed();
      return $block;
  }
}

function invoicely_version_control_version() {
  return '<span>' . t('Github: <a href="@url">@version</a>', array('@url' => 'https://github.com/matthewbaggett/Invoicely', '@version' => substr(ace_get_git_revision(),0,10))) . '</span>';
}

function invoicely_designed_and_developed() {
  return '<span>' . t('<a href="@designer">Designed</a> & <a href="@developer">Developed</a>', array('@designer' => 'mailto:matthew@fouroneone.us', '@developer' => 'mailto:matthew@fouroneone.us')) . '</span>';
}

  /**
 * Implements hook_permission().
 *
 * Defines a permission for managing the mail_system variable.
 */
function invoicely_permission()
{
    return array(
        'view dashboard' => array(
            'title' => t("View Dashboard"),
            'description' => t("View own invoicely dashboard"),
        ),
        'view invoices' => array(
            'title' => t('View Invoices'),
            'description' => t('Allow a user to view their own invoices'),
        ),
        'view receipts' => array(
            'title' => t('View Receipts'),
            'description' => t('Allow a user to view their own receipts'),
        ),
        'view mileage' => array(
          'title' => t('View Mileage'),
          'description' => t('Allow a user to view their own mileage log'),
        ),
    );
}

/**
 * Crunch through a view
 *
 * @param string $file File of the template to call.
 * @param array|object $view Optional view array.
 *
 * @return string
 */
function invoicely_template_view($file, $view = null)
{
    $file = DRUPAL_ROOT . "/" . drupal_get_path('module', 'invoicely') . "/" . $file;
    if (!file_exists($file)) {
        return "Cannot find {$file}";
    }
    extract((array)$view);
    ob_start();
    require($file);
    $markup = ob_get_contents();
    ob_end_clean();

    return $markup;
}

function invoicely_get_currency(){
  return "£";
}