<script>
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = google.visualization.arrayToDataTable(<?php echo json_encode($view->invoice_chart_data); ?>);

    var options = {
      title: 'Payments',
      hAxis: {title: 'Date',  titleTextStyle: {color: '#333'}},
      vAxis: {minValue: 0}
    };

    var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  }
</script>

<div class="dash_chart" id="chart_div"></div>

<?php
$header = array(
  t('Month'),
  t('Financial Year'),
  t('Amount Billed'),
  t('Actions')
);
$rows = array();
// remove first element - Its a heading.
array_shift($view->invoice_chart_data);
$cumulative_amount=0;
foreach($view->invoice_chart_results as $month){
  $date_bits = explode("-", $month->yearmonth);
  $date_fy_bits = explode("-", $month->financial_year);
  $cumulative_amount+=$month[1];
  $rows[] = array(
    $month->yearmonth,
    l($month->financial_year, 'invoices/list', array('query' => array('year' => $date_fy_bits[0], 'month' => $date_fy_bits[1]))),
    "&pound; {$month->amount_paid_cumulative}",
    l("View Invoices in {$month->yearmonth}", 'invoices/list', array('query' => array('year' => $date_bits[0], 'month' => $date_bits[1])))
  );
}
$rows[] = array('Total', "&pound; {$cumulative_amount}", '');
?>
<?php echo theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No invoices'))); ?>
