<script>
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = google.visualization.arrayToDataTable(<?php echo json_encode($view->invoice_chart_data); ?>);

    var options = {
      title: 'Payments',
      hAxis: {title: 'Date',  titleTextStyle: {color: '#333'}},
      vAxis: {minValue: 0}
    };

    var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  }
</script>

<div class="dash_chart" id="chart_div"></div>

<?php
$header = array(
  t('Month'),
  t('Financial Year'),
  t('Amount Billed'),
  t('Actions')
);
$rows = array();
// remove first element - Its a heading.
array_shift($view->invoice_chart_data);
$cumulative_amount=0;
foreach($view->invoice_chart_results as $month){
  $date_bits = explode("-", $month->yearmonth);
  $date_fy_bits = explode("-", $month->financial_year);
  $cumulative_amount+=$month->amount_paid_cumulative;
  $rows[] = array(
    $month->yearmonth,
    l($month->financial_year, 'invoices/list', array('query' => array('year_start' => $date_fy_bits[0], 'year_end' => $date_fy_bits[1], 'month_start' => 4, 'month_end' => 4))),
    t(":currency :amount", array(':currency' => invoicely_get_currency(), ':amount' => $month->amount_paid_cumulative)),
    l("View Invoices in {$month->yearmonth}", 'invoices/list', array('query' => array('year' => $date_bits[0], 'month' => $date_bits[1])))
  );
}
$rows[] = array(t('Total'), '', invoicely_get_currency() . " " . $cumulative_amount, '');
?>
<a class="btn btn-app btn-primary no-radius" href="<?php echo url("invoices/add"); ?>"><i class="icon-edit bigger-230"></i><?php echo t("Add Invoice"); ?></a>
<?php echo theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No invoices'), 'attributes' => array('class' => array('tablesorter')))); ?>
