<?php
$header = array(
  t('Client / Agency'),
  t('Date Issued'),
  t('Invoice Number'),
  t('Amount Charged'),
  t('Paid'),
  t('Notes')
);
$rows = array();
$cumulative_amount = 0;
foreach($view->invoices as $invoice){
  /* @var $invoice invoice_record */
  $cumulative_amount+=$invoice->amount_charged;
  $rows[] = array(
    l($invoice->get_client()->name . ($invoice->get_client()->agency?" ({$invoice->get_client()->agency})":""), "clients/view/{$invoice->get_client()->cid}"),
    $invoice->get_date_issued(),
    l($invoice->invoice_number, "invoices/view/{$invoice->iid}"),
    "&pound; " . $invoice->amount_charged,
    (
      $invoice->paid == "No" ?
        $invoice->amount_charged - $invoice->amount_paid . " unpaid." :
        ($invoice->date_paid?"Yes, on {$invoice->get_date_paid()}":"Yes.")
    ),
    $invoice->notes
  );

}
$rows[] = array('Total', "", "", "&pound; {$cumulative_amount}", '', '');
?>
<?php echo l(t("Add new Invoice"), "invoices/add"); ?>
<?php echo theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No invoices'))); ?>

