<?php
$header = array(
  t('Client / Agency'),
  t('Date Issued'),
  t('Date Paid'),
  t('Lead Time'),
  t('Invoice Number'),
  t('Amount Charged'),
  t('Paid'),
  t('Notes'),
  t('Actions')
);
$rows = array();
$cumulative_amount = 0;
foreach($view->invoices as $invoice){
  /* @var $invoice invoice_record */
  $cumulative_amount+=$invoice->amount_charged;
  $rows[] = array(
    l($invoice->get_client()->name . ($invoice->get_client()->agency?" ({$invoice->get_client()->agency})":""), "clients/view/{$invoice->get_client()->cid}"),
    $invoice->get_date_issued(),
    $invoice->get_date_paid('U')>0?$invoice->get_date_paid() . " " . $invoice->get_date_paid('U'):t('Unknown'),
    $invoice->get_date_paid('U')>0?ceil($invoice->get_date_paid('U') - $invoice->get_date_issued('U') / 86400):t("N/A"),
    l($invoice->invoice_number, "invoices/view/{$invoice->iid}"),
    invoicely_get_currency() . " "  . $invoice->amount_charged,
    (
      $invoice->paid == "No" ?
        "<span class=\"label label-danger arrowed\">" . invoicely_get_currency() . " "  . ($invoice->amount_charged - $invoice->amount_paid) . " " . t("unpaid.") . "</span>" :
        "<span class=\"label label-success arrowed\">" . ($invoice->date_paid ? t("Yes, on :datepaid", array(':datepaid' => $invoice->get_date_paid())) : t("Yes.")) . "</span>"
    ),
    $invoice->notes,
    l("Edit", "invoices/edit/{$invoice->get_id()}")
  );

}
$rows[] = array(t('Total'), "", "", invoicely_get_currency() . " {$cumulative_amount}", '', '');
?>

<?php require_once("buttons.phtml"); ?>

<div class="row">
  <div class="col-sm-8">
    <?php echo theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No invoices'), 'attributes' => array('class' => array('tablesorter')))); ?>
  </div>
  <div class="col-sm-4">
    <div class="dash_chart" id="chart_div"></div>
  </div>
</div>


