<?php
$header = array(
  t('Retailer'),
  t('Name'),
  t('Date first Occurrence'),
  t('Summary'),
  t('Frequency'),
  t('Occurrences'),
  t('Item Count'),
  t('Amount'),
  t('VAT'),
  t('Total')
);
$rows = array();
foreach($view->repeated_receipts as $receipt){
    /* @var $receipt receipt_repeated_record */
    $rows[] = array(
        $receipt->get_retailer()->name,
        $receipt->get_label(),
        $receipt->get_date_first_occurrence('Y-m-d H:i:s'),
        $receipt->get_summary(),
        $receipt->get_frequency()->get_label(),
        $receipt->get_occurrence_dates_html(),
        $receipt->get_number_of_items(),
        invoicely_get_currency() . " " . $receipt->get_total_amount_pretax(),
        invoicely_get_currency() . " " . $receipt->get_total_vat(),
        invoicely_get_currency() . " " . $receipt->get_total_amount()
    );
}
?>
<?php echo theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No receipts'), 'attributes' => array('class' => array('tablesorter')))); ?>

