<?php
$header = array(
  t('Retailer'),
  t('Date first Occurrence'),
  t('Summary'),
  t('Frequency'),
  t('Occurrences'),
);
$rows = array();
foreach($view->repeated_receipts as $receipt){
    /* @var $receipt receipt_repeated_record */
    $rows[] = array(
        $receipt->get_retailer()->name,
        $receipt->get_date_first_occurrence('Y-m-d'),
        $receipt->get_summary(),
        $receipt->get_frequency()->get_label(),
        $receipt->get_occurrence_dates_html(),
    );
}
?>
<?php echo theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No receipts'), 'attributes' => array('class' => array('tablesorter')))); ?>

