<?php
$header = array('Client/Agency', 'Date', 'Invoice Number', 'Amount Charged', 'Paid', 'Notes');
$rows = array();
foreach($view->invoices as $invoice){
  /* @var $invoice invoice_record */
  $rows[] = array(
    $invoice->get_client()->name . ($invoice->get_client()->agency?" ({$invoice->get_client()->agency})":""),
    $invoice->get_date_issued('Y-m-d H:i:s'),
    $invoice->invoice_number,
    "&pound; " . $invoice->amount_charged,
    ($invoice->paid == "No"?$invoice->amount_charged - $invoice->amount_paid . " unpaid.":"Yes"),
    $invoice->notes

  );
}
?>
<?php echo theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No invoices'))); ?>
<?php echo l(t("Add new Invoice"), "invoices/add"); ?>
