<?php
$header = array('Retailer', 'Date', 'Item Count', 'Amount', 'VAT', 'Total');
$rows = array();
foreach($view->receipts as $receipt){
    /* @var $receipt receipt_record */
    $rows[] = array(
        $receipt->get_retailer()->name,
        $receipt->get_date('Y-m-d H:i:s'),
        $receipt->get_number_of_items(),
        "&pound; " . $receipt->get_total_amount_pretax(),
        "&pound; " . $receipt->get_total_vat(),
        "&pound; " . $receipt->get_total_amount()
    );
}
?>
<?php echo theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No receipts'))); ?>
