<?php
$header = array('Date', 'Retailer', 'Item Count', 'Amount', 'VAT');
$rows = array();
foreach($view->receipts as $receipt){
    /* @var $receipt receipt_record */
    $rows[] = array(
        $receipt->get_date('Y-m-d H:i:s'),
        $receipt->get_retailer()->name,
        $receipt->get_number_of_items(),
        $receipt->get_total_amount(),
        $receipt->get_total_vat()
    );
}
?>
<?php echo theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No receipts'))); ?>
