<div class="row">
  <div class="col-sm-12">
    <div class="btn-group">
      <a class="btn btn-danger radius-4" href="<?php echo url("mileage/add"); ?>"><i class="icon-edit bigger-230"></i><?php echo t("Add Journeys"); ?></a>
      <a class="btn btn-danger radius-4" href="<?php echo url("mileage/calendar"); ?>"><i class="icon-edit bigger-230"></i><?php echo t("View Journey Calendar"); ?></a>
      <a class="btn btn-danger radius-4" href="<?php echo url("mileage/import"); ?>"><i class="icon-cloud-upload bigger-230"></i><?php echo t("Import Journeys"); ?></a>
      <a class="btn btn-danger radius-4" href="<?php echo url("mileage/export"); ?>"><i class="icon-cloud-download bigger-230"></i><?php echo t("Export Journeys"); ?></a>
    </div>
  </div>
</div>