<script>
google.setOnLoadCallback(drawChart);
function drawChart() {
    var data = google.visualization.arrayToDataTable(<?php echo json_encode($view->mileage_chart_data); ?>);

    var options = {
        title: 'Mileage this year',
        hAxis: {title: 'Date',  titleTextStyle: {color: '#333'}},
        vAxis: {minValue: 0}
    };

    var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
    chart.draw(data, options);
}
</script>
<div class="row">
  <div class="col-sm-8">
  </div>
  <div class="col-sm-4">
    <div class="dash_chart" id="chart_div"></div>
  </div>
</div>
