<?php
global $user;
$available_financial_years_results = db_query("
  SELECT
    financial_year
  FROM
    invoicely_get_financial_years_available
  WHERE
    uid = {$user->uid}
");
$available_financial_years = array();
foreach($available_financial_years_results as $available_financial_year){
  $available_financial_years[] = $available_financial_year->financial_year;
}
foreach($available_financial_years as $available_financial_year){
  $year_invoice_total_results = active_record_dumb_model::queryOne("
    SELECT
      SUM(amount_paid_cumulative) as amount_paid_cumulative,
      financial_year
    FROM
      invoicely_invoice_view_monthly_totals
    WHERE
      financial_year = '{$available_financial_year}'
      AND uid = {$user->uid}
    GROUP BY financial_year
  ");

  $year_mileage_total_results = active_record_dumb_model::queryOne("
    SELECT
      financial_year,
      distance,
      amount as mileage_allowance
    FROM
      invoicely_mileage_view_yearly_amounts
    WHERE
      financial_year = '{$available_financial_year}'
      AND uid = {$user->uid}
  ");

  $year_receipts_total_results = active_record_dumb_model::queryOne("
    SELECT
      financial_year,
      amount_cumulative
    FROM
      invoicely_reciept_view_yearly_totals
    WHERE
      financial_year = '{$available_financial_year}'
      AND uid = {$user->uid}
  ");

  $total_after_expenses = $year_invoice_total_results->amount_paid_cumulative - $year_receipts_total_results->amount_cumulative - $year_mileage_total_results->mileage_allowance;

  //krumo($year_invoice_total_results, $year_mileage_total_results, $year_receipts_total_results)
  ?>
  <div class="widget">
    <h3><?php echo t("Liability for year :year", array(':year' => $available_financial_year)); ?></h3>
    <dl>
      <dt><?php echo t("Total Invoices"); ?>:</dt>
      <dt><?php echo t(":currency :money", array(':currency' => invoicely_get_currency(), ':money' => $year_invoice_total_results->amount_paid_cumulative)); ?></dt>
      <dt><?php echo t("Total Receipts"); ?>:</dt>
      <dt><?php echo t(":currency :money", array(':currency' => invoicely_get_currency(), ':money' => $year_receipts_total_results->amount_cumulative)); ?></dt>
      <dt><?php echo t("Total Mileage"); ?>:</dt>
      <dd><?php echo t(":miles miles, for :currency :money", array(':miles' => $year_mileage_total_results->distance, ':currency' => invoicely_get_currency(), ':money' => $year_mileage_total_results->mileage_allowance)); ?></dd>
      <dt><?php echo t("Total After Expenses & Mileage"); ?>:</dt>
      <dt><?php echo t(":currency :money", array(':currency' => invoicely_get_currency(), ':money' => $total_after_expenses)); ?></dt>
      <dt><?php echo t("Total Liability"); ?>:</dt>
      <dt><?php echo t(":currency :money", array(':currency' => invoicely_get_currency(), ':money' => $total_after_expenses * 0.20)); ?></dt>
    </dl>
  </div>

<?php } ?>