<div class="row">
  <div class="col-sm-12">
    <div class="btn-group">
      <a class="btn btn-primary radius-4" href="<?php echo url("receipts/add"); ?>"><i class="icon-edit bigger-230"></i><?php echo t("Add Receipt"); ?></a>
      <a class="btn btn-primary radius-4" href="<?php echo url("receipts/import"); ?>"><i class="icon-cloud-upload bigger-230"></i><?php echo t("Import Receipts"); ?></a>
      <a class="btn btn-danger radius-4" href="<?php echo url("receipts/export"); ?>"><i class="icon-cloud-download bigger-230"></i><?php echo t("Export Receipts"); ?></a>
    </div>
  </div>
</div>