<?php
$header = array(
  t('Retailer'),
  t('Date'),
  t('Summary'),
  t('Item Count'),
  t('Amount'),
  t('VAT'),
  t('Total')
);
$rows = array();
foreach($view->receipts as $receipt){
    /* @var $receipt receipt_record */
    $rows[] = array(
        $receipt->get_retailer()->name,
        $receipt->get_date('Y-m-d'),
        $receipt->get_summary(),
        $receipt->get_number_of_items(),
        invoicely_get_currency() . $receipt->get_total_amount_pretax(),
        invoicely_get_currency() . $receipt->get_total_vat(),
        invoicely_get_currency() . $receipt->get_total_amount()
    );
}
?>
<?php echo l(t("Add new Receipt"), "receipts/add"); ?>
<?php echo l(t("Import Receipts"), "receipts/import"); ?>
<?php echo l(t("Export Receipts"), "receipts/export"); ?>
<?php echo theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No receipts'), 'attributes' => array('class' => array('tablesorter')))); ?>

