<?php
$header = array(
  t('Retailer'),
  t('Date'),
  t('Summary'),
  t('Item Count'),
  t('Amount'),
  t('VAT'),
  t('Total')
);
$rows = array();
foreach($view->receipts as $receipt){
    /* @var $receipt receipt_record */
    $rows[] = array(
        $receipt->get_retailer()->name,
        $receipt->get_date('Y-m-d'),
        $receipt->get_summary(),
        $receipt->get_number_of_items(),
        invoicely_get_currency() . $receipt->get_total_amount_pretax(),
        invoicely_get_currency() . $receipt->get_total_vat(),
        invoicely_get_currency() . $receipt->get_total_amount()
    );
}
?>
<a class="btn btn-app btn-primary radius-4" href="<?php echo url("receipts/add"); ?>"><i class="icon-edit bigger-230"></i><?php echo t("Add Receipt"); ?></a>
<a class="btn btn-app btn-primary radius-4" href="<?php echo url("receipts/import"); ?>"><i class="icon-cloud-upload bigger-230"></i><?php echo t("Import Receipts"); ?></a>
<a class="btn btn-app btn-primary radius-4" href="<?php echo url("receipts/export"); ?>"><i class="icon-cloud-download bigger-230"></i><?php echo t("Export Receipts"); ?></a>

<?php echo theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No receipts'), 'attributes' => array('class' => array('tablesorter')))); ?>

