<?php
$header = array(
  t('Retailer'),
  t('Date'),
  t('Summary'),
  t('Item Count'),
  t('Amount'),
  t('VAT'),
  t('Total')
);
$rows = array();
foreach($view->receipts as $receipt){
    /* @var $receipt receipt_record */
    $rows[] = array(
        $receipt->get_retailer()->name,
        $receipt->get_date('Y-m-d'),
        $receipt->get_summary(),
        $receipt->get_number_of_items(),
        invoicely_get_currency() . $receipt->get_total_amount_pretax(),
        invoicely_get_currency() . $receipt->get_total_vat(),
        invoicely_get_currency() . $receipt->get_total_amount()
    );
}
?>
<div class="row">
  <div class="col-sm-12">
    <div class="btn-group">
      <a class="btn btn-primary radius-4" href="<?php echo url("receipts/add"); ?>"><i class="icon-edit bigger-230"></i><?php echo t("Add Receipt"); ?></a>
      <a class="btn btn-primary radius-4" href="<?php echo url("receipts/import"); ?>"><i class="icon-cloud-upload bigger-230"></i><?php echo t("Import Receipts"); ?></a>
      <a class="btn btn-primary radius-4" href="<?php echo url("receipts/export"); ?>"><i class="icon-cloud-download bigger-230"></i><?php echo t("Export Receipts"); ?></a>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-8">
    <?php echo theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No receipts'), 'attributes' => array('class' => array('tablesorter')))); ?>
  </div>
  <div class="col-sm-4"></div>
</div>
